apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: value

spec:
  initContainers:
    - name: init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app

  containers:
    - name: main
      image: biomack/otus-2-web:1.1
      volumeMounts:
        - name: app
          mountPath: /app
      readinessProbe: # Добавим проверку готовности
        httpGet: # веб-сервера отдавать
           path: /index.html # контент
           port: 80
      livenessProbe:
          tcpSocket: { port: 8000 }

  volumes:
    - name: app
      emptyDir: {}